# Generated by Django 5.0.14 on 2025-08-08 13:31

import django.core.validators
import django.db.models.deletion
import django_percentagefield.db.models.fields.percentage_field
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("vacancies", "0002_vacancy_grades_vacancy_role_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Disability",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Disabilities",
            },
        ),
        migrations.CreateModel(
            name="EthnicGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ethnicity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Ethnicities",
            },
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SexualOrientation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AggregatedApplicationStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "percent_applications",
                    django_percentagefield.db.models.fields.percentage_field.PercentageField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(
                                Decimal("1"),
                                message="Ensure this value is less than or equal to 100.",
                            ),
                        ],
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "vacancy",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.vacancy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VacancyStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                ("total_applications", models.PositiveIntegerField(null=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "vacancy",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.vacancy",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="aggregatedapplicationstatistic",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "content_type", "object_id"),
                name="aggregated_application_unique_vacancy_total_applications",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancystatistic",
            constraint=models.UniqueConstraint(
                fields=("vacancy",), name="vacancy_statistic_unique_vacancy"
            ),
        ),
    ]
