# Generated by Django 5.0.14 on 2025-10-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_statistics', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('vacancies', '0003_vacancy_person_spec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AggregatedApplicationCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('count', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='aggregatedapplicationcount',
            constraint=models.UniqueConstraint(fields=('vacancy', 'content_type', 'object_id'), name='aggregated_application_count_unique_constraint'),
        ),
    ]
