# Generated by Django 5.0.14 on 2025-05-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("application_statistics", "0001_initial"),
        ("roles", "0001_initial"),
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agegroupstatistic",
            name="vacancy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancies.vacancy",
            ),
        ),
        migrations.AddField(
            model_name="disabilitystatistic",
            name="disability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disability_statistics",
                to="application_statistics.disability",
            ),
        ),
        migrations.AddField(
            model_name="disabilitystatistic",
            name="vacancy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancies.vacancy",
            ),
        ),
        migrations.AddField(
            model_name="ethnicgroupstatistic",
            name="ethnic_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ethnic_group_statistics",
                to="application_statistics.ethnicgroup",
            ),
        ),
        migrations.AddField(
            model_name="ethnicgroupstatistic",
            name="vacancy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancies.vacancy",
            ),
        ),
        migrations.AddField(
            model_name="ethnicitystatistic",
            name="ethnicity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ethnicity_statistics",
                to="application_statistics.ethnicity",
            ),
        ),
        migrations.AddField(
            model_name="ethnicitystatistic",
            name="vacancy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancies.vacancy",
            ),
        ),
        migrations.AddField(
            model_name="genderstatistic",
            name="gender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gender_statistics",
                to="application_statistics.gender",
            ),
        ),
        migrations.AddField(
            model_name="genderstatistic",
            name="vacancy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancies.vacancy",
            ),
        ),
        migrations.AddField(
            model_name="jobgradestatistic",
            name="job_grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_grade_statistics",
                to="roles.grade",
            ),
        ),
        migrations.AddField(
            model_name="jobgradestatistic",
            name="vacancy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancies.vacancy",
            ),
        ),
        migrations.AddField(
            model_name="roletypestatistic",
            name="role_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_type_statistics",
                to="roles.roletype",
            ),
        ),
        migrations.AddField(
            model_name="roletypestatistic",
            name="vacancy",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vacancies.vacancy",
            ),
        ),
        migrations.AddConstraint(
            model_name="agegroupstatistic",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "age_group"), name="unique_vacancy_age_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="disabilitystatistic",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "disability"), name="unique_vacancy_disability"
            ),
        ),
        migrations.AddConstraint(
            model_name="ethnicgroupstatistic",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "ethnic_group"), name="unique_vacancy_ethnic_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="ethnicitystatistic",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "ethnicity"), name="unique_vacancy_ethnicity"
            ),
        ),
        migrations.AddConstraint(
            model_name="genderstatistic",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "gender"), name="unique_vacancy_gender"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobgradestatistic",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "job_grade"), name="unique_vacancy_job_grade"
            ),
        ),
        migrations.AddConstraint(
            model_name="roletypestatistic",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "role_type"), name="unique_vacancy_role_type"
            ),
        ),
    ]
