# Generated by Django 5.0.14 on 2025-10-16 16:00

import os
import csv
from collections import defaultdict
from django.db import migrations
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


def populate_data(apps, schema_editor):
    """
    Performs the initial, one-time population of applicant region counts.
    """
    # --- 1. Get all the models we need ---
    Dandi = apps.get_model('oleeo', 'Dandi')
    Region = apps.get_model('application_statistics', 'Region')
    AggregatedApplicationCount = apps.get_model('application_statistics', 'AggregatedApplicationCount')
    ContentTypeModel = apps.get_model('contenttypes', 'ContentType')

    # --- 2. Load the postcode-to-region mapping file ---
    print("\nLoading postcode-to-region mapping file...")
    region_lookup = {}
    fixture_path = os.path.join(settings.BASE_DIR, 'jao_backend', 'application_statistics', 'fixtures', 'postcode_regions.csv')
    try:
        with open(fixture_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                outward_code = row['Postcode']
                region_name = row['NUTS1 region']
                if outward_code and region_name:
                    region_lookup[outward_code.upper()] = region_name
        print(f"  Successfully loaded {len(region_lookup)} postcode mappings.")
    except FileNotFoundError:
        raise FileNotFoundError(f"CRITICAL: The mapping file was not found at {fixture_path}. The migration cannot proceed.")

    # --- 3. Create the Region objects in the database ---
    print("Populating the Region lookup table...")
    region_name_to_object_map = {}
    unique_region_names = set(region_lookup.values())
    for region_name in unique_region_names:
        region_obj, created = Region.objects.get_or_create(
        description=region_name,
    defaults={'last_updated': timezone.now()}
    )
        region_name_to_object_map[region_name] = region_obj
    print(f"  Ensured {len(unique_region_names)} Region objects exist.")

        # --- 4. Process all raw applicant data from Oleeo ---
    print("Querying and processing applicant postcodes from Oleeo DB...")
    vacancy_stats = defaultdict(lambda: defaultdict(int))

    print("  Fetching list of existing vacancies from jao-backend DB...")
    Vacancy = apps.get_model('vacancies', 'Vacancy')
    existing_vacancy_ids = set(Vacancy.objects.values_list('id', flat=True))
    print(f"  Found {len(existing_vacancy_ids)} existing vacancies to process.")


    queryset = Dandi.objects_for_ingest.using('oleeo_upstream').select_related(
        'application', 'postcode'
    ).filter(
        application__vacancy_id__in=existing_vacancy_ids
    ).iterator(chunk_size=2000)

    processed_count = 0
    for dandi_record in queryset:
        postcode_str = dandi_record.postcode.postcode_desc
        if not postcode_str:
            continue
        outward_code = postcode_str.split(' ')[0].upper()
        region_name = region_lookup.get(outward_code)
        if region_name:
            vacancy_id = dandi_record.application.vacancy_id
            region_obj = region_name_to_object_map.get(region_name)
            if region_obj:
                vacancy_stats[vacancy_id][region_obj] += 1
        processed_count += 1
        if processed_count % 50000 == 0:
            print(f"  ...processed {processed_count} applicants...")
    print(f"  Finished processing. Found data for {len(vacancy_stats)} vacancies.")

    # --- 5. Prepare the new AggregatedApplicationCount records ---
    print("Preparing new summary records for the database...")
    counts_to_create = []

    region_content_type = ContentTypeModel.objects.get_for_model(Region)

    aggregated_count_ctype = ContentTypeModel.objects.get_for_model(AggregatedApplicationCount)

    for vacancy_id, region_counts in vacancy_stats.items():
        for region_obj, count in region_counts.items():
            counts_to_create.append(
                AggregatedApplicationCount(
                    vacancy_id=vacancy_id,
                    content_type=region_content_type,
                    object_id=region_obj.pk,
                    count=count,
                    updated_at=timezone.now(),
                    polymorphic_ctype=aggregated_count_ctype
                )
            )

    # --- 6. Save everything to the database ---
    print(f"Saving {len(counts_to_create)} new applicant region count records...")
    if counts_to_create:
        AggregatedApplicationCount.objects.bulk_create(counts_to_create, batch_size=500, ignore_conflicts=True)
        print("  Bulk creation complete.")
    else:
        print("  No new records to create.")


class Migration(migrations.Migration):

    dependencies = [
        ('application_statistics', '0002_region_aggregatedapplicationcount_and_more'),
        ('oleeo', '0001_initial'),
    ]


    operations = [
        migrations.RunPython(populate_data, migrations.RunPython.noop),
    ]