# Generated by Django 5.0.14 on 2025-10-21 08:20

from django.db import migrations
from django.db.models import F

def merge_regions(apps, schema_editor):
    """
    Finds and merges duplicate 'Yorkshire and the Humber' region entries,
    correctly handling cases where statistics exist for both variations.
    """
    Region = apps.get_model('application_statistics', 'Region')
    AggregatedApplicationCount = apps.get_model('application_statistics', 'AggregatedApplicationCount')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    CORRECT_NAME = "Yorkshire and The Humber"
    INCORRECT_NAME = "Yorkshire and the Humber"

    try:
        correct_region = Region.objects.get(description=CORRECT_NAME)
        incorrect_region = Region.objects.get(description=INCORRECT_NAME)
    except Region.DoesNotExist:
        print(f"\nSkipping merge: Could not find both region entries.")
        return

    print(f"\nMerging '{INCORRECT_NAME}' (ID: {incorrect_region.pk}) into '{CORRECT_NAME}' (ID: {correct_region.pk})...")

    region_content_type = ContentType.objects.get_for_model(Region)

    # Get all statistics records pointing to the INCORRECT region
    stats_to_merge = AggregatedApplicationCount.objects.filter(
        content_type=region_content_type,
        object_id=incorrect_region.pk
    )

    merged_count = 0
    conflict_count = 0
    for incorrect_stat in stats_to_merge:
        # Check if a statistic for the CORRECT region ALREADY exists for this vacancy
        correct_stat, created = AggregatedApplicationCount.objects.get_or_create(
            vacancy_id=incorrect_stat.vacancy_id,
            content_type=region_content_type,
            object_id=correct_region.pk,
            # Provide defaults in case it needs to be created (shouldn't happen often)
            defaults={
                'count': incorrect_stat.count,
                'updated_at': incorrect_stat.updated_at,
                'polymorphic_ctype_id': incorrect_stat.polymorphic_ctype_id
            }
        )

        if not created:
            # If the correct stat already existed, ADD the counts together
            correct_stat.count = F('count') + incorrect_stat.count
            correct_stat.save()
            conflict_count += 1
            # Now delete the incorrect one, as its count has been merged
            incorrect_stat.delete()
        else:
             # If the correct stat didn't exist, we just created it using the defaults
             # which effectively "moved" the incorrect stat over.
             merged_count += 1 # Count how many were simply moved
             # Since get_or_create just created the 'correct' version, delete the old incorrect one
             incorrect_stat.delete()


    print(f"  Processed {stats_to_merge.count()} incorrect statistics records.")
    print(f"  Merged counts for {conflict_count} conflicting vacancy records.")
    print(f"  Directly moved {merged_count - conflict_count} non-conflicting records.") # Correction: merged_count reflects total processed.

    # Now that all statistics have been merged or moved, delete the duplicate region entry.
    incorrect_region.delete()
    print(f"  Deleted the duplicate region entry '{INCORRECT_NAME}'.")
    print("  Merge complete.")

class Migration(migrations.Migration):

    dependencies = [
        ('application_statistics', '0003_populate_applicant_region_counts'),
    ]

    operations = [
        migrations.RunPython(merge_regions, migrations.RunPython.noop)
    ]
