# Generated by Django 5.0.14 on 2025-06-27 21:55

import django.contrib.postgres.fields
import jao_backend.oleeo.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("shorthand_name", models.TextField(unique=True)),
            ],
            options={
                "verbose_name": "CS Job grade",
                "ordering": ["description"],
            },
        ),
        migrations.CreateModel(
            name="OleeoGradeGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "description",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                (
                    "shorthand",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "OLEEO role groups",
                "ordering": ["description"],
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
        ),
        migrations.CreateModel(
            name="OleeoRoleTypeGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "description",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
        ),
        migrations.CreateModel(
            name="RoleType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
