# Generated by Django 5.0.14 on 2025-07-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"ordering": ["description"]},
        ),
    ]
