api: hypercorn src.asgi:application --bind 0.0.0.0:8001 --reload
celery_beat: celery -A jao_backend.common.celery beat
celery_worker: celery -A jao_backend.common.celery worker --loglevel=INFO
celery_flower: celery -A jao_backend.common.celery flower
