# Generated by Django 5.0.14 on 2025-06-13 14:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestListAgeGroup",
            fields=[
                ("age_group_id", models.AutoField(primary_key=True, serialize=False)),
                ("age_group_desc", models.TextField()),
                ("row_last_updated", models.DateTimeField()),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TestVacancies",
            fields=[
                ("vacancy_id", models.IntegerField(primary_key=True, serialize=False)),
                ("vacancy_title", models.TextField()),
                ("salary_minimum", models.TextField(blank=True, null=True)),
                ("salary_maximum_optional", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
