# Generated by Django 5.0.14 on 2025-06-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testvacancies",
            options={"managed": True},
        ),
    ]
