# Generated by Django 5.0.14 on 2025-07-10 15:12

import django.db.models.deletion
import jao_backend.oleeo.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_alter_testvacancies_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestVacanciesTimestamps",
            fields=[
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="vacanciestimestamps",
                        serialize=False,
                        to="tests.testvacancies",
                    ),
                ),
                ("live_date", models.DateTimeField()),
                ("closing_date", models.DateTimeField()),
            ],
            options={
                "managed": True,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
        ),
    ]
