# Generated by Django 5.0.14 on 2025-04-29 17:05

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [
        VectorExtension()
    ]