# Generated by Django 5.0.14 on 2025-06-18 10:28

import jao_backend.common.db.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    jao_backend.common.db.fields.uuid7_field.UUIDField(
                        default=jao_backend.common.db.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
    ]
