# Generated by Django 4.2 on 2025-03-26 12:58

from django.db import migrations, models
import jao_backend.common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    jao_backend.common.fields.UUIDField(
                        default=jao_backend.common.fields.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
    ]
