# Generated by Django 5.0.14 on 2025-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCluster',
            fields=[
                ('cluster_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='cluster_id',
            field=models.IntegerField(db_index=True, default=-1),
        ),
    ]
