# Generated by Django 5.0.14 on 2025-05-06 16:17

import django.db.models.deletion
import jao_backend.common.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("common", "0001_initial_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="EmbeddingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmbeddingBase",
            fields=[
                (
                    "embedding_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="embeddings.embedding",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=768, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("embeddings.embedding",),
        ),
        migrations.CreateModel(
            name="EmbeddingLarge",
            fields=[
                (
                    "embedding_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="embeddings.embedding",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=1024, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("embeddings.embedding",),
        ),
        migrations.CreateModel(
            name="EmbeddingSmall",
            fields=[
                (
                    "embedding_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="embeddings.embedding",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=512, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("embeddings.embedding",),
        ),
        migrations.CreateModel(
            name="EmbeddingTiny",
            fields=[
                (
                    "embedding_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="embeddings.embedding",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=384, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("embeddings.embedding",),
        ),
        migrations.CreateModel(
            name="EmbeddingXL",
            fields=[
                (
                    "embedding_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="embeddings.embedding",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=1536, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("embeddings.embedding",),
        ),
        migrations.AddField(
            model_name="embedding",
            name="embedding_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="embeddings.embeddingmodel",
            ),
        ),
        migrations.CreateModel(
            name="EmbeddingTag",
            fields=[
                (
                    "uuid",
                    jao_backend.common.fields.UUIDField(
                        db_index=True,
                        default=jao_backend.common.fields.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                (
                    "version",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The version of the embedding tag.",
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="The embedding model.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="embeddings.embeddingmodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Embedding Tags",
            },
        ),
        migrations.AddConstraint(
            model_name="embeddingtag",
            constraint=models.UniqueConstraint(
                fields=("uuid", "version"), name="unique_embedding_versioned_ag"
            ),
        ),
    ]
