# Generated by Django 5.0.14 on 2025-07-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("embeddings", "0001_initial"),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="CS Jobs vacancy ID [5-6 characters]",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(help_text="Last updated date and time."),
                ),
                ("live_date", models.DateTimeField()),
                ("closing_date", models.DateTimeField()),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Vacancy is marked as deleted."
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The minimum salary.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The maximum salary.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, help_text="Job title.", null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Job description.", null=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Blerb about teams.", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancies",
            },
        ),
        migrations.CreateModel(
            name="VacancyEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The chunk ID of the embedding.",
                        null=True,
                    ),
                ),
                (
                    "embedding",
                    models.ForeignKey(
                        help_text="The embedding.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embeddings.embedding",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="The tag of the embedding.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embeddings.embeddingtag",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        help_text="The vacancy.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancy Embeddings",
            },
        ),
        migrations.CreateModel(
            name="VacancyGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        help_text="The grade of the vacancy.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roles.grade",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        help_text="The vacancy.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancy Grades",
            },
        ),
        migrations.CreateModel(
            name="VacancyRoleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.ForeignKey(
                        help_text="The role type of the vacancy.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roles.roletype",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        help_text="The vacancy.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancy Grades",
            },
        ),
        migrations.AddConstraint(
            model_name="vacancyembedding",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "tag", "embedding", "chunk_index"),
                name="unique_vacancy_embedding_chunk",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vacancyembedding",
            unique_together={("vacancy", "tag", "embedding")},
        ),
        migrations.AlterUniqueTogether(
            name="vacancygrade",
            unique_together={("vacancy", "grade")},
        ),
        migrations.AlterUniqueTogether(
            name="vacancyroletype",
            unique_together={("vacancy", "role_type")},
        ),
    ]
