# Generated by Django 5.0.14 on 2025-07-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="grades",
            field=models.ManyToManyField(
                help_text="The grades of the vacancy.",
                through="vacancies.VacancyGrade",
                to="roles.grade",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="role_types",
            field=models.ManyToManyField(
                help_text="The role types of the vacancy.",
                through="vacancies.VacancyRoleType",
                to="roles.roletype",
            ),
        ),
    ]
