# Generated by Django 5.0.14 on 2025-09-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_grade_options'),
        ('vacancies', '0002_vacancy_grades_vacancy_role_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='person_spec',
            field=models.TextField(blank=True, help_text='The person specification of a vacancy', null=True),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['is_deleted'], name='vacancies_v_is_dele_f7cd9b_idx'),
        ),
    ]
