# Generated by Django 5.0.14 on 2025-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('vacancies', '0003_vacancy_person_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='skills.skill'),
        ),
    ]
