# Generated by Django 5.0.14 on 2025-10-23 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0003_vacancy_person_spec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyTextAggregate',
            fields=[
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aggregated_text', serialize=False, to='vacancies.vacancy')),
                ('all_personal_statements', models.TextField(blank=True)),
                ('all_employment_history', models.TextField(blank=True)),
                ('all_previous_skills', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField(unique=True)),
                ('personal_statement', models.TextField(blank=True, null=True)),
                ('employment_history', models.TextField(blank=True, null=True)),
                ('previous_skill_experience', models.TextField(blank=True, null=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_texts', to='vacancies.vacancy')),
            ],
        ),
    ]
