# Generated by Django 5.0.14 on 2025-10-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancytextaggregate',
            name='skills_extracted',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this text has been processed by the skills-worker.'),
        ),
    ]
