# Generated by Django 5.0.14 on 2025-10-16 16:45

import django.db.models.deletion
import django.db.models.manager
import jao_backend.oleeo.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
        ('application_id', models.IntegerField(primary_key=True, serialize=False)),
        ('vacancy', models.ForeignKey(db_column='vacancy_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='oleeo.vacancies')),
        ('application_status', models.ForeignKey(blank=True, db_column='application_status_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='oleeo.listapplicationstatus')),
        ('applicant_type', models.ForeignKey(blank=True, db_column='applicant_type_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='oleeo.listapplicanttype')),
        ('employment_history', models.TextField(blank=True, null=True)),
        ('row_last_updated', models.DateTimeField()),
    ],
            options={
                'db_table': 'Applications',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListAgeGroup',
            fields=[
                ('age_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('age_group_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_AgeGroup',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListApplicantType',
            fields=[
                ('applicant_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_type_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_ApplicantType',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListApplicationStatus',
            fields=[
                ('application_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_status_desc', models.TextField()),
                ('application_status_list_id', models.IntegerField()),
                ('terminal_status', models.BooleanField()),
                ('status_group_desc', models.TextField(blank=True, null=True)),
                ('row_last_updated', models.DateTimeField()),
                ('status_progress_desc', models.TextField(blank=True, null=True)),
                ('status_group_detailed_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'List_ApplicationStatus',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListBusinessArea',
            fields=[
                ('business_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_area_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_BusinessArea',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListCityTown',
            fields=[
                ('city_town_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_town_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_CityTown',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListDepartment',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_Department',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListDisability',
            fields=[
                ('disability_id', models.AutoField(primary_key=True, serialize=False)),
                ('disability_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_Disability',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListEthnicGroup',
            fields=[
                ('ethnic_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('ethnic_group_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_EthnicGroup',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListEthnicity',
            fields=[
                ('ethnicity_id', models.AutoField(primary_key=True, serialize=False)),
                ('ethnicity_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_Ethnicity',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListGender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_Gender',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListJobGrade',
            fields=[
                ('job_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_grade_desc', models.TextField()),
                ('job_grade_shorthand', models.TextField(blank=True, null=True)),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_JobGrade',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListLocationType',
            fields=[
                ('location_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_type_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_LocationType',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListPostcode',
            fields=[
                ('postcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_Postcode',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListProfession',
            fields=[
                ('profession_id', models.AutoField(primary_key=True, serialize=False)),
                ('profession_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_Profession',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListRegion',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_Region',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListReligion',
            fields=[
                ('religion_id', models.AutoField(primary_key=True, serialize=False)),
                ('religion_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_Religion',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListSexualOrientation',
            fields=[
                ('sexual_orientation_id', models.AutoField(primary_key=True, serialize=False)),
                ('sexual_orientation_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_SexualOrientation',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListTypeOfRole',
            fields=[
                ('type_of_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_role_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_TypeOfRole',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListVacancyApproach',
            fields=[
                ('vacancy_approach_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacancy_approach_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_VacancyApproach',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListVacancyPostcode',
            fields=[
                ('vacancy_postcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacancy_postcode_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_VacancyPostcode',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListVacancyStatus',
            fields=[
                ('vacancy_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacancy_status_desc', models.TextField()),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'List_VacancyStatus',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('vacancy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vacancy_title', models.TextField()),
                ('number_of_jobs', models.IntegerField(blank=True, null=True)),
                ('salary_minimum', models.TextField(blank=True, null=True)),
                ('salary_maximum_optional', models.TextField(blank=True, null=True)),
                ('job_summary', models.TextField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('person_specification', models.TextField(blank=True, null=True)),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'Vacancies',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dandi',
            fields=[
                    ('application', models.OneToOneField(db_column='application_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='dandi', serialize=False, to='oleeo.applications')),
                    ('disability', models.ForeignKey(blank=True, db_column='disability_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dandi', to='oleeo.listdisability')),
                    ('sexual_orientation', models.ForeignKey(blank=True, db_column='sexual_orientation_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dandi', to='oleeo.listsexualorientation')),
                    ('age_group', models.ForeignKey(blank=True, db_column='age_group_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dandi', to='oleeo.listagegroup')),
                    ('ethnic_group', models.ForeignKey(blank=True, db_column='ethnic_group_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dandi', to='oleeo.listethnicgroup')),
                    ('religion', models.ForeignKey(blank=True, db_column='religion_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dandi', to='oleeo.listreligion')),
                    ('ethnicity', models.ForeignKey(blank=True, db_column='ethnicity_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dandi', to='oleeo.listethnicity')),
                    ('gender', models.ForeignKey(blank=True, db_column='gender_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dandi', to='oleeo.listgender')),
                    ('postcode', models.ForeignKey(blank=True, db_column='postcode_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dandi', to='oleeo.listpostcode')),
                    ('row_last_updated', models.DateTimeField()),
                ],

            
            options={
                'db_table': 'DandI',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesTimestamps',
            fields=[
                ('vacancy', models.ForeignKey(db_column='vacancy_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='oleeo.vacancies')),
                ('vacancy_created_in_draft_first_in', models.DateTimeField(blank=True, null=True)),
                ('recruitment_review_most_recent', models.DateTimeField(blank=True, null=True)),
                ('recruitment_review_first_in', models.DateTimeField(blank=True, null=True)),
                ('most_recent_posting_live', models.DateTimeField(blank=True, null=True)),
                ('most_recent_posting_closing', models.DateTimeField(blank=True, null=True)),
                ('live_date', models.DateTimeField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('last_status_change', models.DateTimeField(blank=True, null=True)),
                ('posting_live_date_latest', models.DateTimeField(blank=True, null=True)),
                ('posting_closing_date_latest', models.DateTimeField(blank=True, null=True)),
                ('sift_results_released', models.DateTimeField(blank=True, null=True)),
                ('sift_results_ready_first_in', models.DateTimeField(blank=True, null=True)),
                ('sift_results_ready_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_interview_1_results_released', models.DateTimeField(blank=True, null=True)),
                ('interview_2_results_released', models.DateTimeField(blank=True, null=True)),
                ('interview_3_results_released', models.DateTimeField(blank=True, null=True)),
                ('interview_4_results_released', models.DateTimeField(blank=True, null=True)),
                ('interview_1_results_ready_first_in', models.DateTimeField(blank=True, null=True)),
                ('interview_2_results_ready_first_in', models.DateTimeField(blank=True, null=True)),
                ('interview_3_results_ready_first_in', models.DateTimeField(blank=True, null=True)),
                ('interview_4_results_ready_first_in', models.DateTimeField(blank=True, null=True)),
                ('interview_1_results_ready_most_recent', models.DateTimeField(blank=True, null=True)),
                ('interview_2_results_ready_most_recent', models.DateTimeField(blank=True, null=True)),
                ('interview_3_results_ready_most_recent', models.DateTimeField(blank=True, null=True)),
                ('interview_4_results_ready_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_interview_1_on_hold_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_interview_1_on_hold_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_interview_2_on_hold_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_interview_2_on_hold_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_interview_3_on_hold_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_interview_3_on_hold_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_interview_4_on_hold_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_interview_4_on_hold_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_sift_on_hold_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_sift_on_hold_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_interview_1_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_interview_1_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_interview_2_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_interview_2_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_interview_3_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_interview_3_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_interview_4_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_interview_4_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_pre_employment_checks_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_pre_employment_checks_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_sift_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_at_sift_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_complete_first_in', models.DateTimeField(blank=True, null=True)),
                ('vacancy_complete_most_recent', models.DateTimeField(blank=True, null=True)),
                ('vacancy_created_in_draft_most_recent', models.DateTimeField(blank=True, null=True)),
                ('live_posted_first_in', models.DateTimeField(blank=True, null=True)),
                ('live_posted_most_recent', models.DateTimeField(blank=True, null=True)),
                ('interview_1_results_ready_to_be_released', models.DateTimeField(blank=True, null=True)),
                ('interview_2_results_ready_to_be_released', models.DateTimeField(blank=True, null=True)),
                ('interview_3_results_ready_to_be_released', models.DateTimeField(blank=True, null=True)),
                ('interview_4_results_ready_to_be_released', models.DateTimeField(blank=True, null=True)),
                ('sift_results_ready_to_be_released', models.DateTimeField(blank=True, null=True)),
                ('vacancy_history_last_changed', models.DateTimeField(blank=True, null=True)),
                ('row_last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'VacanciesTimestamps',
                'managed': False,
            },
            bases=(models.Model, jao_backend.oleeo.base_models.UpstreamModelMixin),
            managers=[
                ('objects_for_ingest', django.db.models.manager.Manager()),
            ],
        ),
    ]
